### ISSUE TITLE
Error when loading font in v2.0.0 on Ubuntu

### ISSUE THREAD

**Issue by cschol** [64MM4-KN1F3/AuntyLangtons-FREE-V2#3]
The following error is shown in the Rack log when the module is loaded in the module browser:

```
[1.233 warn src/window/Window.cpp:829 loadFont] Cannot read file res/DSEG7ClassicMini-Regular.ttf
```

**Comment by 64MM4-KN1F3** [comment]
Hi @cschol - I've removed the custom font in latest update (doesn't affect module functionality). Haven't been able to compile for Ubuntu to test but hopefully this fixes that warning.
